version: "3.2"     
services:           
  mongodb:          
    image: mongo    
    restart: always 
    environment:    
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
   
    container_name: "mongodb"
    ports:                
      - "27017:27017"     